### ISSUE TITLE
Create Security Context using the openshift golang Client

### ISSUE THREAD

**Issue by prateek1192** [openshift/client-go#138]
I am trying to create SCC using OC client in golang. I see that the documentation is very sparse for it. I am trying to consume "github.com/openshift/client go/security/clientset/versioned/typed/security/v1" amd creating a scc  using this like scclient.SecurityContextConstraints().Create(). Is there a way I can pass yaml to it ?

Can we have some examples regarding this in the docs ?

**Comment by danielm-codefresh** [comment]
/reopen
So is there a way to achieve this?
