### ISSUE TITLE
How to get list of `DeploymentConfig` in a controller

### ISSUE THREAD

**Issue by mic4ael** [openshift/client-go#145]
Hey, I am looking for a way to get a list of all `DeploymentConfig`s in my operator.
I ended up with something like the following but I am kind of unsure how I am supposed to instantiate an `AppsV1Client`.

```go
import (
    openshiftApiv1 "github.com/openshift/api/apps/v1"
)

openshiftClient := openshiftCLientv1.New() // what do i have to pass to New?
if err := openshiftClient.List(context.TODO(), goCli.MatchingLabels(labels), webEosDeploymentConfigList); err != nil {
    return nil, err
}
```

**Comment by faizanbashir** [comment]
@mic4ael did you find any solution for this?

**Comment by mic4ael** [comment]
@faizanbashir Nope, unfortunately I didn't look into this since I created the issue.

**Comment by faizanbashir** [comment]
Unfortunately, no one from Openshift cares to clarify.
