### ISSUE TITLE
Add k8s dependencies tracking step and start proper tag management

### ISSUE THREAD

**Issue by xakepp35** [openshift/client-go#241]
we are using `go.mod` file from this repo as a referene to "which versions of k8s packages would we use" in our go.mod/sum files

its very good, that with reecnt releases you started to track and bump the versions of k8s, and i want to kindly ask you to improve it a little bit.

so [here, in a new 4.15 go mod](https://github.com/openshift/client-go/blob/release-4.15/go.mod) you bumped only 2 of 4 packages; it led to having:
```
	k8s.io/api v0.26.3
	k8s.io/apimachinery v0.26.3
	k8s.io/client-go v0.26.1
	k8s.io/code-generator v0.26.1
```

whicch doesnt look "consistent". what i am offering - is to add extra step and extra bit of attention - before creating new release tag - can you please check for fresh versions of all 4 repos, bump them in your `go.mod` as a single piece (imagine that old code-generator potentially may be incompatible with newer api, or vice versa) and make them same version? i would thank you in advane

also, theres a side issue. `go get` has 2 ways bumping things - 1 way is thay you arent using tags at all, but get repo@commit only, and there are no tags - then go get will fetch you latest commit from master
Or, second way - is you start track tags. Even go pakages `x/text`, `/sys`, `/net`, and so on - switched to tags tracking! Here it looks like you are switched to do tags, because creating first tag switches go package management system into "tagged" operation mode.
go get doesnt pull latest commit from main, but pulls latest tag.
So having `v3.9.0` tag forces it to use tags instead of latest commit. hovewer you dont provide v4.13.0, v4.14.0 tags, which makes latest to freeze to `v3.9.0` - this solution is not friendly with `go get github.com/openshift/client-go`
![image](https://user-images.githubusercontent.com/10540956/233055705-fcbb8145-7731-417e-afc9-8d148089397c.png)

Can you please elaborate abit, on request, in order of importance:
- make k8s.io packages be single version in your `go.mod`
- evaluate for fresh versions of k8s.io before doing release
- start releases taging for your project on github, because you already have `v3.9.0` tag - to be aligned and friendly with tag system that everyone is using. as a developer i know that branches are convenient for providers ability to support and send fixes, but tags are extremely important for package users. you can create `v4.15.1`, `v4.15.2` tags with minor fixes inside release-4.15 branch

that will allow easy and consistent update of ocp/k8s clients with single simple call `go get github.com/openshift/client-go`

sincerely, golang developers.

**Comment by JoelSpeed** [comment]
I will bring this up internally, but typically we don't tag OpenShift releases on repositories. 

Using the master branch should be avoided since that is a development branch and therefore would be considered unsupported and may have changes introduced mid-release that cause issues.

If you are using this repository, I would recommend only pulling from branches `release-4.yy`, where the `yy` represents the version of OpenShift you are building your tooling against.

There are normally only very minor changes to this repository within a release, so it is unlikely you would need to revendor within a release branch unless some specific API is added or bug is fixed, but we typically do not backport API/client-go changes after an initial release is to be made

**Comment by xakepp35** [comment]
Please,
> start releases taging for your project on github, **because you already have v3.9.0 tag** - to be aligned and friendly with tag system that everyone is using. as a developer i know that branches are convenient for providers ability to support and send fixes, but tags are extremely important for package users

golang does not care about branches, only about tags! package users should not be affected by selected developement scheme - be it branch based, master, whatever else branches - you just pull thing and it will just pull you latest tag, (no matter what branching model internally you prefer to use)
