### ISSUE TITLE
support for older openshift?

### ISSUE THREAD

**Issue by daxzhuo** [openshift/client-go#27]
Hi,
I'm currently using openshift 1.5 , now I need client-go to interact with openshift, there is no release for openshift 1.5, is this client-go backward compatible?

**Comment by deads2k** [comment]
> Hi,
> I'm currently using openshift 1.5 , now I need client-go to interact with openshift, there is no release for openshift 1.5, is this client-go backward compatible?

This repo is not compatible with v1.5.  It is backwards compatible to the point when the openshift APIs were moved to groups, so that is 3.6.  

I opened https://github.com/openshift/client-go/pull/28 to help explain it in more detail.

**Comment by daxzhuo** [comment]
I see. Thanks.
Any suggestion about using API client to interact with openshift before v3.6? As far as I know, the only way is hack oc code.

**Comment by deads2k** [comment]
> I see. Thanks.
> Any suggestion about using API client to interact with openshift before v3.6? As far as I know, the only way is hack oc code.

It will be hard. We produced clients back then, but they were tied into the rest of openshift, so you had to find odd levels of deps (this was pre-glide days).  If memory serves, you'd be dealing with https://github.com/openshift/origin/tree/release-1.5/pkg/client and depending on what you wanted to do with serialized input hacking the `oc` code is a fair plan.
