### ISSUE TITLE
Contribution Guide 

### ISSUE THREAD

**Issue by ralphg6** [openshift/client-go#3]
I want contribute with this repository, and others also will want! 

Let's define tasks and the contribution guideline!

I have golang projects needing consume the Openshift Origin API!

The Glide was a great choice!

**Comment by deads2k** [comment]
@ralphg6 since this was opened, we've finalized the structure we want and added new generators for informers and listers.  Can you take a look at what we have available now and make a few suggestions for areas you'd like to see improvement in so we can focus the effort?
