### ISSUE TITLE
Support for `oc new-app`

### ISSUE THREAD

**Issue by containscafeine** [openshift/client-go#30]
Hi,
Are there any plans for introducing support for `oc new-app` features via client-go?

**Comment by deads2k** [comment]
> Hi,
> Are there any plans for introducing support for oc new-app features via client-go?

No.  This repo is about providing fairly low level APIs for interacting with the openshift REST API with typed clients and some building blocks on there for writing a controller.  `oc new-app` is heavily focused on a CLI experience for "create me some resources I might like based on this thing I've linked".  The logic for "resources I might like" is very particular and opinionated in way that we would not guarantee as an API.
