### ISSUE TITLE
Export of Resources

### ISSUE THREAD

**Issue by Floble** [openshift/client-go#35]
Hi,

I am looking for a way to export OpenShift resources, like deploymentconfigs and rolebindings, with the golang client. Using the CLI, I perform the following command:

`oc get dc -o yaml --export=true > /tmp/example.yaml`

How can I perform this action with the golang client? It seems that I cannot pass ```ExportOptions``` to the ```Get()``` function of, for instance, ```RoleBindings```.

Can you give a short example on how to do this?

Thanks!

**Comment by deads2k** [comment]
Server-side export is likely to go away.  There are multiple competing intentions about what export means and we've come to the conclusion that the use-case is best served by doing a straight GET of the resources and later choosing how you want to manipulate it before using the value.  This allows maximum flexibility and lets you change your mind later.

See some other thoughts here: https://github.com/kubernetes/kubernetes/issues/24855#issuecomment-365407438
