### ISSUE TITLE
Error while deleting services 

### ISSUE THREAD

**Issue by surajnarwade** [openshift/client-go#40]
I am trying to delete bunch of services using following line,

```
err = c.kubeClient.CoreV1().Services(c.namespace).DeleteCollection(&metav1.DeleteOptions{},metav1.ListOptions{LabelSelector: selector})
```

I am getting following error,

```
the server does not allow this method on the requested resource
```

**Comment by deads2k** [comment]
That error is correct.  Services don't support deletecollection. I've opened a pull to fix the client upstream https://github.com/kubernetes/kubernetes/pull/63861 .  You'll need to list the services and then delete them.
