### ISSUE TITLE
Client go compatible with openshift < 3.5

### ISSUE THREAD

**Issue by Nexucis** [openshift/client-go#46]
Hello,

I'm currently working with openshift v3.5 and unfortunately for me, I can't upgrade the version.

I was looking in the code client-go to see if I can use it even if I don't have the correct version of openshift. And what a disappointment I had when I seen that the `APIPath` and the `GroupVersion` was hardcoding in each package.

It will be nice if we can have the APIPath and the GroupVersion in the parameter of the method of `setConfigDefaults` for each endpoints.  (Well as this method as package private, maybe we can another method like setLegacyConfig) 

As far I can see, it seems that all the code has been developed in order to be retro compatible. For example in [github.com/openshift/api/{endpoint like route}/v1/register](https://github.com/openshift/api/blob/master/route/v1/register.go) provides a const `LegacyGroupName` that could be used in the client-go. 

Is it something that can interest you ?

**Comment by deads2k** [comment]
This client and the associated generators are only designed to work with groupified APIs.  While the effort *seems* small, supporting the legacy `/oapi` endpoints with generators not designed to work with them is impractical.

We introduced the current, groupified APIs that are compatible with this client in 3.6, so the compatibility range is fairly broad.
