### ISSUE TITLE
Cannot Create route

### ISSUE THREAD

**Issue by Setheck** [openshift/client-go#92]
When attempting to create a Route, I get the following error
`encoding is not allowed for this codec: *versioning.codec` 
I cannot figure out what is wrong, or what the error actually means. 
I'm targeting minishift running 3.11 locally, I can create routes via yaml `oc create -f` and through the console but using the client-go api based more or less off this example https://docs.okd.io/latest/go_client/serializing_and_deserializing.html 
I just get the error above. Any help is appreciated. 

I would also love to know about any sample code or docs that are more helpful, the single build example included in the repo is not very encompassing.

**Comment by Setheck** [comment]
After a long struggle, it appears that passing the RESTClient() interface from a kubernetes clientset to the routev1client.New() function, does not work. 
I'm not sure if this is a bug or by design, but the example below fails with the error I mention.
```
import (
        "k8s.io/client-go/kubernetes"
	routev1client "github.com/openshift/client-go/route/clientset/versioned/typed/route/v1"
        routev1 "github.com/openshift/api/route/v1"
)

func createRoute(clientset  *kubernetes.Clientset, obj *routev1.Route) error {
    ...
    _,err := routev1client.New(clientset.RESTClient()).Routes("my-ns").Create(obj)
    return err
}
```

In order to get around this i have to store the *rest.Config and pass that around, then 
do something like the following
```
    client, _ := routev1client.NewForConfig(cfg)
    _, err := client.Routes("my-ns").Create(obj)
    retur err
```

**Comment by scniro** [comment]
@Setheck I am so happy I found this issue. I was down the rabbit hole with another library that involves custom resources & specific clientsets, and was seeing the exact same error. I suspect this is not specific to routes, but rather the patters around working with cientsets. Thank you for opening this up!
