### ISSUE TITLE
Getting undefined error message after changes in `route/clientset/versioned/scheme/register.go`

### ISSUE THREAD

**Issue by borntorock** [openshift/client-go#93]
While creating the custom controller using Kubernetes go-client and OpenShift go-client, I'm getting the issue
```
/go/src/github.com/openshift/client-go/route/clientset/versioned/scheme/register.go:39:2: undefined: "k8s.io/apimachinery/pkg/util/runtime".Must
```
This error seems to be an impact after the changes being done here: https://github.com/openshift/client-go/blob/master/route/clientset/versioned/scheme/register.go

I'm just importing the route package from the OpenShift go-client in my custom controller as:
```

	"k8s.io/apimachinery/pkg/fields"
	"k8s.io/apimachinery/pkg/util/runtime"
	"k8s.io/apimachinery/pkg/util/wait"
	"k8s.io/client-go/kubernetes"
	"k8s.io/client-go/rest"
	"k8s.io/client-go/tools/cache"
	"k8s.io/client-go/util/workqueue"
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

	v1 "github.com/openshift/api/route/v1"
	routev1 "github.com/openshift/client-go/route/clientset/versioned/typed/route/v1"
```

Any help would be highly appreciated.

CC/ @deads2k

**Comment by seenickcode** [comment]
@borntorock, would you have any further updates on this? I'm getting the same issue.

**Comment by borntorock** [comment]
@seenickcode Unfortunately no, this issue still persists atleast for me. I have reverted back to release-3.11 version.
